apiVersion: v1
kind: Pod
metadata:
  name: random-number-pod
spec:
  containers:
    - name: random-generator
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - RANDOM_NUM=$(expr $RANDOM % 100 + 1);
          echo $RANDOM_NUM > /opt/number.out;
          sleep 3600;
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: data-volume 
          mountPath: /opt
  volumes:
    - name: data-volume 
      hostPath:  # instead of hostPath, you can use emptyDir, configMap, cloud storages, etc.
        path: /data
        type: Directory