#deploy nginx with nodeport service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterip-nginx-deployment
  labels:
    app: nginx-clusterip
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-clusterip
  template:
    metadata:
      labels:
        app: nginx-clusterip
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
---
# service for clusterip-nginx
apiVersion: v1
kind: Service
metadata:
  name: clusterip-nginx-svc
spec:
  type: ClusterIP
  selector:
    app: nginx-clusterip
  ports:
    - protocol: TCP
      port: 80 #port of the service
      targetPort: 80 #port of the container
      